from investint.widgets.company.drop_down           import *
from investint.widgets.company.general_information import *
from investint.widgets.company.dmpl                import *
from investint.widgets.company.cvm_statement       import *
from investint.widgets.company.statement_period    import *
from investint.widgets.company.statement           import *
from investint.widgets.company.financials          import *
from investint.widgets.company.indicator           import *
from investint.widgets.company.widget              import *